/**
 * The definitive pin: our verifier reproduces EXACTLY what Plivo's own
 * `validateV3Signature` accepts — via FIXED VECTORS generated by running the
 * real plivo-node SDK (v3Security.js) offline on 2026-08-29, each vector
 * confirmed `plivoAccepts: true` before being frozen here.
 *
 * Why vectors and not a devDependency on `plivo`: the SDK drags a vulnerable
 * `form-data` transitive (GHSA-fjxv-7rqg-78g4) that the dependency audit
 * rightly blocks. Frozen third-party-generated vectors give the same
 * protection this guard exists for: a reference that CANNOT drift in
 * lockstep with our reimplementation (the hand-written reference did exactly
 * that, reproducing the missing-`?` bug and staying green while every live
 * webhook was rejected).
 *
 * Regeneration procedure (if the algorithm ever changes upstream):
 *   npm i plivo && node -e "see commit message of this file's introduction"
 */
import { describe, it, expect } from 'vitest';
import { plivoV3Signature, verifyPlivoSignature } from '../integrations/plivo-phone/verify.js';

const TOKEN = 'fake-plivo-token-for-tests-000';
const URL = 'https://project-hello-api.fly.dev/api/integrations/plivo/answer';

/** Each `expected` was produced AND validated by plivo-node's own code. */
const VECTORS: Array<{
  name: string; nonce: string;
  params: Record<string, string>; expected: string;
}> = [
  {
    name: 'typical answer callback',
    nonce: 'nonce-typical',
    params: { To: 'sip:x@lk', From: '+918031729057', CallUUID: 'u-1', 'X-PH-Hello-Attempt': 'deadbeef-0000-4000-8000-000000000000' },
    expected: '2CsMeBMrEZfU1QAUH9yDfA/asKHkq5wI0phUyTxGP+c=',
  },
  {
    name: 'single param',
    nonce: 'nonce-single',
    params: { CallUUID: 'abc' },
    expected: 'VYszpvXjiKa9/r3iYs62C/37vHGg99ww7BEmcVZxCmw=',
  },
  {
    name: 'keys needing sort',
    nonce: 'nonce-sorting',
    params: { Zeta: '1', Alpha: '2', mid: '3' },
    expected: 'E+7fLX5LmLvBoLGU2jQEhtlBInq1PLWU99ic7ex16rE=',
  },
  {
    name: 'empty params',
    nonce: 'nonce-empty',
    params: {},
    expected: 'dbJzRNCCVZ44490gybaP/AgTChuJH6QFEa01Q24ae0Y=',
  },
];

describe('plivo V3 — pinned to vectors generated by the real plivo-node SDK', () => {
  for (const v of VECTORS) {
    it(`our signature equals the SDK-produced one: ${v.name}`, () => {
      expect(plivoV3Signature(TOKEN, URL, v.params, v.nonce)).toBe(v.expected);
    });

    it(`our verifier accepts the SDK-produced signature: ${v.name}`, () => {
      const res = verifyPlivoSignature(TOKEN, {
        signedUrl: URL, params: v.params,
        signatureHeader: v.expected, nonceHeader: v.nonce,
      });
      expect(res.ok).toBe(true);
    });
  }
});
